### ISSUE TITLE
Possible to add a new menu item specifically for Apparel?

### ISSUE THREAD

**Issue by foxnne** [Ideki/UIPlayNiceExample#1]
Hello!

I have been wanting to try to make a new mod that adds a button to the apparel screen, not the overall inventory screen, that allows you to remove all apparel on the button press. This would make changing outfits when you are wearing a lot of different items (like with Zone79's mods) much easier and more convenient.

I just wanted to ask if there was any chance this is possible using UIPlayNice? I assume right now we can only add a button to the overall inventory menu, though I suppose a "Disrobe" or something button in the inventory that stays around with the apparel menu would be fine too.

Thanks!

**Comment by Ideki** [comment]
I think it should be feasible.
If I add your mod to the InventoryMenu that would give you access to the inventory UI, its events and button bar,

Looking at the InventoryMenu UI code I see that they use a List of categories so you would add your button to the button bar, then hide it.
Then you could check for the selected entry and if that matches what you need, you make your button visible.
So something like 
`menu.CategoryList_mc.selectedEntry.iFilterFlags == InventoryItemUtils.ICF_APPAREL.`

I think that should do the trick.
You might need to check on a timer, or see if there is an event incoming each time you change category that you could use as a trigger to refresh your button.

**Comment by foxnne** [comment]
Thank you so much for the detailed information, I really appreciate it! I will try to dig into this in the coming days.

**Comment by foxnne** [comment]
Closing because this isn't actually an issue.
